### ISSUE TITLE
Is it possible to support routable engines?

### ISSUE THREAD

**Issue by Cryrivers** [poteto/ember-crumbly#100]

**Comment by dguettler** [comment]
What are the issues you're seeing when trying to use it in combination with routable engines?

**Comment by mrkirchner** [comment]
What i am seeing is the following error 

`Assertion Failed: [ember-crumbly] Could not find a current route
Error
    at assert (http://localhost:4200/assets/vendor.js:20974:13)
    at assert (http://localhost:4200/assets/vendor.js:32725:34)
    at Class.get (http://localhost:4200/engines-dist/authoring/assets/engine-vendor.js:5072:9)
    at ComputedPropertyPrototype.get (http://localhost:4200/assets/vendor.js:32381:28)
    at Object.get (http://localhost:4200/assets/vendor.js:37374:19)
    at RootPropertyReference.compute (http://localhost:4200/assets/vendor.js:30337:26)
    at RootPropertyReference.value (http://localhost:4200/assets/vendor.js:30204:45)
    at ArrayIterable.iterate (http://localhost:4200/assets/vendor.js:29960:26)
    at IterationArtifacts.isEmpty (http://localhost:4200/assets/vendor.js:59895:58)
    at IterablePresenceReference.value (http://localhost:4200/assets/vendor.js:64296:36)`

Ill try to dig a bit more to get some more information.

**Comment by mrkirchner** [comment]
Looks like in bread-crumbs.js

` currentRouteName: readOnly('applicationRoute.controller.currentRouteName'),`

currentRouteName is undefined since controller is pretty much empty.  Hopefully that give you enough info to try to fix it.   If you need me to do anything let me know.
@dguettler

**Comment by ascudder** [comment]
I encountered this same problem with one of our projects, so think I found where this issue is coming from. 

In the [`_lookupRoute` function in the bread-crumbs component](https://github.com/poteto/ember-crumbly/blob/master/addon/components/bread-crumbs.js#L82), the `getOwner(this)` function can only look up the routes that exist in the parent application. So, when it encounters a route that is inside of a routable engine, `_lookupRoute` returns `undefined` because it can't find the route because the route is owned by the engine, not the parent application that's hosting the engine. 

After looking at how the Ember Engines project [addressed a similar problem in their project](https://github.com/emberjs/ember.js/pull/14545/files#diff-985dc4a078da4636eff18be21aa7f9e6R1087), I believe that using the routing service and the `getHandler(routeName)` function will allow the route object to get looked up whether the route belongs to the parent app or an engine. I'm starting to work on a PR now that will hopefully help resolve this.

**Comment by GCheung55** [comment]
@dguettler with #143 merged, what are the next steps to publishing a new version to NPM?
